# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
