# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20151207_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wine',
        ),
    ]
